SDLOBJ = $(CORE_DIR)/libretro

SDLOBJS := \
	$(SDLOBJ)/sdl-libretro/src/SDL_error.o $(SDLOBJ)/sdl-libretro/src/SDL_fatal.o \
	$(SDLOBJ)/sdl-libretro/src/SDL.o $(SDLOBJ)/sdl-libretro/src/audio/SDL_wave.o \
	$(SDLOBJ)/sdl-libretro/src/audio/SDL_audiodev.o $(SDLOBJ)/sdl-libretro/src/audio/SDL_mixer_MMX.o \
	$(SDLOBJ)/sdl-libretro/src/audio/SDL_mixer_m68k.o $(SDLOBJ)/sdl-libretro/src/audio/SDL_audiocvt.o \
	$(SDLOBJ)/sdl-libretro/src/audio/SDL_audio.o $(SDLOBJ)/sdl-libretro/src/audio/SDL_mixer.o \
	$(SDLOBJ)/sdl-libretro/src/audio/SDL_mixer_MMX_VC.o $(SDLOBJ)/sdl-libretro/src/cdrom/SDL_cdrom.o \
	$(SDLOBJ)/sdl-libretro/src/cpuinfo/SDL_cpuinfo.o $(SDLOBJ)/sdl-libretro/src/events/SDL_active.o \
	$(SDLOBJ)/sdl-libretro/src/events/SDL_quit.o $(SDLOBJ)/sdl-libretro/src/events/SDL_mouse.o \
	$(SDLOBJ)/sdl-libretro/src/events/SDL_events.o $(SDLOBJ)/sdl-libretro/src/events/SDL_keyboard.o \
	$(SDLOBJ)/sdl-libretro/src/events/SDL_expose.o $(SDLOBJ)/sdl-libretro/src/events/SDL_resize.o \
	$(SDLOBJ)/sdl-libretro/src/file/SDL_rwops.o $(SDLOBJ)/sdl-libretro/src/stdlib/SDL_string.o \
	$(SDLOBJ)/sdl-libretro/src/stdlib/SDL_malloc.o $(SDLOBJ)/sdl-libretro/src/stdlib/SDL_iconv.o \
	$(SDLOBJ)/sdl-libretro/src/stdlib/SDL_getenv.o $(SDLOBJ)/sdl-libretro/src/stdlib/SDL_qsort.o \
	$(SDLOBJ)/sdl-libretro/src/stdlib/SDL_stdlib.o $(SDLOBJ)/sdl-libretro/src/thread/SDL_thread.o \
	$(SDLOBJ)/sdl-libretro/src/timer/SDL_timer.o $(SDLOBJ)/sdl-libretro/src/video/SDL_cursor.o \
	$(SDLOBJ)/sdl-libretro/src/video/SDL_blit_0.o $(SDLOBJ)/sdl-libretro/src/video/SDL_yuv.o \
	$(SDLOBJ)/sdl-libretro/src/video/SDL_bmp.o $(SDLOBJ)/sdl-libretro/src/video/SDL_video.o \
	$(SDLOBJ)/sdl-libretro/src/video/SDL_yuv_mmx.o $(SDLOBJ)/sdl-libretro/src/video/SDL_surface.o \
	$(SDLOBJ)/sdl-libretro/src/video/SDL_pixels.o $(SDLOBJ)/sdl-libretro/src/video/SDL_stretch.o \
	$(SDLOBJ)/sdl-libretro/src/video/SDL_blit_A.o $(SDLOBJ)/sdl-libretro/src/video/SDL_blit_N.o \
	$(SDLOBJ)/sdl-libretro/src/video/SDL_blit_1.o $(SDLOBJ)/sdl-libretro/src/video/SDL_blit.o \
	$(SDLOBJ)/sdl-libretro/src/video/SDL_yuv_sw.o $(SDLOBJ)/sdl-libretro/src/video/SDL_RLEaccel.o \
	$(SDLOBJ)/sdl-libretro/src/video/SDL_gamma.o $(SDLOBJ)/sdl-libretro/src/joystick/SDL_joystick.o \
	$(SDLOBJ)/sdl-libretro/src/video/libretro/SDL_LIBRETROmouse.o \
	$(SDLOBJ)/sdl-libretro/src/video/libretro/SDL_LIBRETROevents.o \
	$(SDLOBJ)/sdl-libretro/src/video/libretro/SDL_LIBRETROvideo.o \
	$(SDLOBJ)/sdl-libretro/src/video/libretro/SDL_LIBRETROkeyboard.o $(SDLOBJ)/sdl-libretro/src/joystick/libretro/SDL_sysjoystick.o \
	$(SDLOBJ)/sdl-libretro/src/audio/libretro/SDL_LIBRETROaudio.o \
	$(SDLOBJ)/sdl-libretro/src/loadso/dummy/SDL_sysloadso.o 

ifeq ($(platform), unix)
SDLOBJS += $(SDLOBJ)/sdl-libretro/src/cdrom/linux/SDL_syscdrom.o \
$(SDLOBJ)/sdl-libretro/src/thread/pthread/SDL_syscond.o \
	$(SDLOBJ)/sdl-libretro/src/thread/pthread/SDL_syssem.o $(SDLOBJ)/sdl-libretro/src/thread/pthread/SDL_sysmutex.o \
	$(SDLOBJ)/sdl-libretro/src/thread/pthread/SDL_systhread.o  \
	$(SDLOBJ)/sdl-libretro/src/timer/libretro/SDL_systimer.o 
endif

ifeq ($(platform), win)
SDLOBJS += $(SDLOBJ)/sdl-libretro/src/cdrom/win32/SDL_syscdrom.o \
	$(SDLOBJ)/sdl-libretro/src/thread/generic/SDL_syscond.o \
	$(SDLOBJ)/sdl-libretro/src/thread/win32/SDL_syssem.o $(SDLOBJ)/sdl-libretro/src/thread/win32/SDL_sysmutex.o \
	$(SDLOBJ)/sdl-libretro/src/thread/win32/SDL_systhread.o \
	$(SDLOBJ)/sdl-libretro/src/timer/win32/SDL_systimer.o 
endif


ifeq ($(platform), wincross64)
SDLOBJS += $(SDLOBJ)/sdl-libretro/src/cdrom/win32/SDL_syscdrom.o \
	$(SDLOBJ)/sdl-libretro/src/thread/generic/SDL_syscond.o \
	$(SDLOBJ)/sdl-libretro/src/thread/win32/SDL_syssem.o $(SDLOBJ)/sdl-libretro/src/thread/win32/SDL_sysmutex.o \
	$(SDLOBJ)/sdl-libretro/src/thread/win32/SDL_systhread.o \
	$(SDLOBJ)/sdl-libretro/src/timer/win32/SDL_systimer.o 
endif

ifeq ($(platform), wiiu)
SDLOBJS += $(SDLOBJ)/sdl-libretro/src/cdrom/dummy/SDL_syscdrom.o\
	$(SDLOBJ)/sdl-libretro/src/thread/pthread/SDL_syscond.o \
	$(SDLOBJ)/sdl-libretro/src/thread/pthread/SDL_syssem.o $(SDLOBJ)/sdl-libretro/src/thread/pthread/SDL_sysmutex.o \
	$(SDLOBJ)/sdl-libretro/src/thread/pthread/SDL_systhread.o   \
	$(SDLOBJ)/sdl-libretro/src/timer/libretro/SDL_systimer.o 
endif

ATARI800_OBJS = \
	$(CORE_DIR)/src/afile.o \
	$(CORE_DIR)/src/antic.o \
	$(CORE_DIR)/src/atari.o \
	$(CORE_DIR)/src/binload.o \
	$(CORE_DIR)/src/cartridge.o \
	$(CORE_DIR)/src/cassette.o \
	$(CORE_DIR)/src/compfile.o \
	$(CORE_DIR)/src/cfg.o \
	$(CORE_DIR)/src/cpu.o \
	$(CORE_DIR)/src/crc32.o \
	$(CORE_DIR)/src/devices.o \
	$(CORE_DIR)/src/esc.o \
	$(CORE_DIR)/src/gtia.o \
	$(CORE_DIR)/src/img_tape.o \
	$(CORE_DIR)/src/log.o \
	$(CORE_DIR)/src/memory.o \
	$(CORE_DIR)/src/monitor.o \
	$(CORE_DIR)/src/pbi.o \
	$(CORE_DIR)/src/pia.o \
	$(CORE_DIR)/src/pokey.o \
	$(CORE_DIR)/src/rtime.o \
	$(CORE_DIR)/src/sio.o \
	$(CORE_DIR)/src/sysrom.o \
	$(CORE_DIR)/src/util.o \
$(CORE_DIR)/src/sdl/init.o  \
$(CORE_DIR)/src/videomode.o  \
$(CORE_DIR)/src/sdl/main.o  \
$(CORE_DIR)/src/sdl/video.o  \
$(CORE_DIR)/src/sdl/video_sw.o  \
$(CORE_DIR)/src/sdl/input.o  \
$(CORE_DIR)/src/sdl/palette.o  \
$(CORE_DIR)/src/pbi_proto80.o  \
$(CORE_DIR)/src/af80.o  \
$(CORE_DIR)/src/bit3.o  \
$(CORE_DIR)/src/input.o  \
$(CORE_DIR)/src/statesav.o  \
$(CORE_DIR)/src/ui_basic.o  \
$(CORE_DIR)/src/ui.o  \
$(CORE_DIR)/src/artifact.o  \
$(CORE_DIR)/src/colours.o  \
$(CORE_DIR)/src/colours_ntsc.o  \
$(CORE_DIR)/src/colours_pal.o  \
$(CORE_DIR)/src/colours_external.o  \
$(CORE_DIR)/src/screen.o  \
$(CORE_DIR)/src/cycle_map.o  \
$(CORE_DIR)/src/emuos_altirra.o  \
$(CORE_DIR)/src/pbi_mio.o  \
$(CORE_DIR)/src/pbi_bb.o  \
$(CORE_DIR)/src/pbi_scsi.o  \
$(CORE_DIR)/src/sdl/sound.o  \
$(CORE_DIR)/src/pokeysnd.o \
$(CORE_DIR)/src/mzpokeysnd.o \
$(CORE_DIR)/src/remez.o  \
$(CORE_DIR)/src/sndsave.o  \
$(CORE_DIR)/src/sound.o  \
$(CORE_DIR)/src/pbi_xld.o  \
$(CORE_DIR)/src/voicebox.o  \
$(CORE_DIR)/src/votrax.o  \
$(CORE_DIR)/src/votraxsnd.o  \
$(CORE_DIR)/src/ide.o  \
$(CORE_DIR)/src/xep80.o  \
$(CORE_DIR)/src/xep80_fonts.o  \
$(CORE_DIR)/src/filter_ntsc.o  \
$(CORE_DIR)/src/atari_ntsc/atari_ntsc.o  \
$(CORE_DIR)/src/pal_blending.o


COBJS = $(ATARI800_OBJS)  $(SDLOBJS) 

